[package]
name = "halogen"
version = "0.1.1"
authors = ["Ryan Jacobs <ryanjacobs@utexas.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {git = "https://github.com/clap-rs/clap"}
